# -*- coding: utf-8 -*-
"""BAP Lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aFbQRJcubozPCIsP-4W1_l5pVSqyCFLz

##Name: Pranay Singhvi

##UID: 2021300126

Data Importing and Exporting:

● Read a CSV file into a pandas Data Frame

● Export a Data Frame to an Excel file.

● Load JSON data into DataFrame

● (Bonus) Data insight or visualization

# 1. Importing Necessary Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# 2. Read a CSV file into a pandas Data Frame"""

df = pd.read_csv('startup_funding.csv')
df.head()

"""# 3.Export a Data Frame to an Excel file."""

df.to_excel('startup.xlsx')

"""# 4. Load JSON data into DataFrame"""

df2 = pd.read_json('Indian.json')
df2.head()

df3 = pd.json_normalize(df2['states'])
df3.head()

df3.to_excel('island.xlsx')

"""# 5.(Bonus) Data insight or visualization

## Q) Which sector do most startups work on?
"""

df["Industry Vertical"].value_counts().head(20).plot(kind="bar",figsize=(5,5))

"""The startup landscape indicated that the consumer internet sector had experienced significant growth, emerging as one of the largest and most dynamic spaces for startups. Following closely, the technology sector also demonstrated substantial activity, showcasing the ongoing trend of innovation and entrepreneurship in both consumer-facing digital platforms and underlying technological advancements."""